source 'http://git.code.oa.com/T-CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target '${POD_NAME}' do
  ${INCLUDED_PODS}

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

  end
end
